### ISSUE TITLE
Not found for architecture arm64

### ISSUE THREAD

**Issue by alexander-storozhenko** [redis/hiredis#1033] opened 2021-12-21 19:35 UTC
Hello! I'm getting this error when try to build project arm64 architecture (macos m1):
```
Undefined symbols for architecture arm64:
  "_redisConnect", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture arm64
```
when I use structures from the library everything is fine, but the functions do not want to be linked

**Comment by michael-grunder** [comment] 2021-12-21 19:58
Is your version of hiredis compiled for `amd64`?

You can do something like this to check:

```bash
file file /path/to/libhiredis.dylib
```

On my machine it's here, but it may be in `Cellar` if you used homebrew.
```bash
❯ file /usr/local/lib/libhiredis.1.0.3-dev.dylib
/usr/local/lib/libhiredis.1.0.3-dev.dylib: Mach-O 64-bit dynamically linked shared library arm64'
```

**Comment by michael-grunder** [comment] 2021-12-22 20:56
Going to close this because it's not a bug in hiredis but I am happy to help you work through the problem if you need it.

**Closed by michael-grunder** 2021-12-22 20:56 UTC

**Comment by alexander-storozhenko** [comment] 2021-12-22 21:07
Thanks a lot, I forgot to close the issue myself, the problem was with incorrect linking of the library in the project.
