### ISSUE TITLE
adapters/libevent.h:155: undefined reference to hi_calloc

### ISSUE THREAD

**Issue by tomarus** [redis/hiredis#758] opened 2020-02-04 09:22 UTC
Hey,

I get this error since a few days. I'm using the libevent adapter. Probably has to do with the recent alloc changes from #754

` /usr/local/include/hiredis/adapters/libevent.h:155: undefined reference to `hi_calloc(unsigned long, unsigned long)'`

Thanks for looking into this :)

**Comment by michael-grunder** [comment] 2020-02-04 16:16
Almost certainly, but can you provide a bit more information about how you're building hiredis?

I'm not able to reproduce this.  Do you perhaps need a `make install` of hiredis?

**Comment by tomarus** [comment] 2020-02-04 16:34
Hi, we basically do a clean clone on a fresh docker image (buildpack-deps:buster) during each build.

>  $ git clone https://github.com/redis/hiredis.git
>  Cloning into 'hiredis'...
>  $ make -C hiredis install && rm -rf hiredis
>  make: Entering directory '/builds/src/nnd/hiredis'
>  cc -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb net.c
>  cc -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb hiredis.c
>  cc -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb sds.c
>  cc -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb async.c
>  cc -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb read.c
>  cc -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb sockcompat.c
>  cc -std=c99 -pedantic -c -O3 -fPIC   -Wall -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb alloc.c
>  cc -shared -Wl,-soname,libhiredis.so.0.14 -o libhiredis.so net.o hiredis.o sds.o async.o read.o sockcompat.o alloc.o 
>  ar rcs libhiredis.a net.o hiredis.o sds.o async.o read.o sockcompat.o alloc.o
>  Generating hiredis.pc for pkgconfig...
>  mkdir -p /usr/local/include/hiredis /usr/local/include/hiredis/adapters /usr/local/lib
>  cp -pPR hiredis.h async.h read.h sds.h alloc.h /usr/local/include/hiredis
>  cp -pPR adapters/*.h /usr/local/include/hiredis/adapters
>  cp -pPR libhiredis.so /usr/local/lib/libhiredis.so.0.14
>  cd /usr/local/lib && ln -sf libhiredis.so.0.14 libhiredis.so
>  cp -pPR libhiredis.a /usr/local/lib
>  mkdir -p /usr/local/lib/pkgconfig
>  cp -pPR hiredis.pc /usr/local/lib/pkgconfig
>  make: Leaving directory '/builds/src/nnd/hiredis'
> 

In our code we use these 3 includes:

> #include <hiredis/hiredis.h>
> #include <hiredis/async.h>
> #include <hiredis/adapters/libevent.h>

We have used this for the past few years with success, but maybe we forgot to update something on our part in the mean time?

**Comment by michael-grunder** [comment] 2020-02-04 17:13
In your application how are you linking with hiredis?  `-lhiredis` or are you using `libhiredis.a`?

Perhaps this is a version mismatch?  If you're linking dynamically you could check using `ldd`

Something like this would work:

```bash
$ ldd your-app
	libhiredis.so.0.14 => /usr/local/lib/libhiredis.so.0.14 (0x00007f9fbb875000)
```

I created a [small example repo](https://github.com/michael-grunder/hiredis-example-libevent) which gets hiredis and then runs via libevent, but I'm not seeing this issue (either when linking dynamically or statically).

**Comment by michael-grunder** [comment] 2020-02-04 18:03
My small test repo also works building with a Dockerfile and the build image you referenced.

```bash
git clone https://github.com/michael-grunder/hiredis-example-libevent.git
cd hiredis-example-libevent && git checkout docker && docker build .
```

**Comment by tomarus** [comment] 2020-02-04 18:15
Thanks a lot, interesting, it looks a lot the same as we build it, nothing really special.

We use `pkg-config --static` btw.

Our final link command looks something like this:

```g++ our/objects.oo -lpthread -ldl -lz -Wl,-Bstatic `pkg-config --libs --static glib-2.0 openssl hiredis libevent_openssl jsoncpp` -Wl,-Bdynamic -no-pie -g -o ../output```

Also pkg-config doesn't show anything suspicious:

```$ pkg-config --libs --static hiredis
-L/usr/local/lib -lhiredis
$ ls -la /usr/local/lib/libhiredis*
-rw-r--r-- 1 root root 500458 Feb  4 18:00 /usr/local/lib/libhiredis.a
lrwxrwxrwx 1 root root     18 Feb  4 18:00 /usr/local/lib/libhiredis.so -> libhiredis.so.0.14
-rwxr-xr-x 1 root root 328416 Feb  4 18:00 /usr/local/lib/libhiredis.so.0.14
```
I will try and test your test-repo in our build environment tomorrow and see what comes out of that. Thanks for your feedback so far.

**Comment by michael-grunder** [comment] 2020-02-04 18:40
I know what the issue is and I'll get a fix up later today.

We're missing an `extern "C"` declaration.

**Comment by tomarus** [comment] 2020-02-04 18:48
> I know what the issue is and I'll get a fix up later today.
> 
> We're missing an `extern "C"` declaration.

Oh that's really awesome you found something!

Thanks again for your hard work!

**Comment by michael-grunder** [comment] 2020-02-04 20:03
> Oh that's really awesome you found something!

No problem, thanks for the report.

I'll keep the issue open until #759 is merged

**Comment by michael-grunder** [comment] 2020-02-09 21:34
Closing in favor of #764

**Closed by michael-grunder** 2020-02-09 21:34 UTC
