### ISSUE TITLE
There seems to be a memory leak in my example code.

### ISSUE THREAD

**Issue by hsnks100** [redis/hiredis#900] opened 2020-11-30 15:59 UTC
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <errno.h>

#include <hiredis.h>
#include <async.h>
#include <adapters/libevent.h>
void onKeyspaceMessage(redisAsyncContext *c, void *reply, void *privdata)
{
    redisReply *r = (redisReply *) reply;
    if (reply == NULL) return;

    printf("Got keyspace event notification from REDIS.. \n");
    if (r->type == REDIS_REPLY_ARRAY) { for (int j = 0; j < r->elements; j++) { printf("%u) %s\n", j, r->element[j]->str); } }
    return;
}
void getCallback(redisAsyncContext *c, void *r, void *privdata) {
    redisReply *reply = r;
    if (reply == NULL) {
        if (c->errstr) {
            printf("errstr: %s\n", c->errstr);
        }
        return;
    }
    printf("argv[%s]: %s\n", (char*)privdata, reply->str);

    /* Disconnect after receiving the reply to GET */
    redisAsyncDisconnect(c);
}

void connectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        return;
    }
    printf("Connected...\n");
}

void afterRedis();
void disconnectCallback(const redisAsyncContext *c, int status) {
    if (status != REDIS_OK) {
        printf("Error: %s\n", c->errstr);
        /* return; */
    }
    printf("Disconnected...\n");
    usleep(1000000);
    afterRedis();
}

void afterRedis() {

    /* redisEnableKeepAlive(c); */
    struct event_base *base = event_base_new();
    redisOptions options = {0};
    REDIS_OPTIONS_SET_TCP(&options, "*", *);
    struct timeval tv = {0};
    tv.tv_sec = 1;
    options.connect_timeout = &tv;


    redisAsyncContext *c = redisAsyncConnectWithOptions(&options);
    if (c->err) {
        /* Let *c leak for now... */
        printf("Error: %s\n", c->errstr);
        return 1;
    }

    redisLibeventAttach(c,base);

    redisAsyncSetConnectCallback(c,connectCallback);
    redisAsyncSetDisconnectCallback(c,disconnectCallback);
    redisAsyncCommand(c, NULL, NULL, "auth @****");
    redisAsyncCommand(c, NULL, NULL, "config set notify-keyspace-events KEA");
    redisAsyncCommand(c, NULL, NULL, "config timeout 0");
    redisAsyncCommand(c, NULL, NULL, "config tcp-keepalive 0");
    redisAsyncCommand(c, getCallback, (char*)"end-1", "GET key");
    redisAsyncCommand(c, onKeyspaceMessage, (char*)"end-1", "PSUBSCRIBE __keyspace@0__:mirror_setting");
    event_base_dispatch(base);

    printf("--end\n");
}
int main (int argc, char **argv) {
#ifndef _WIN32
    signal(SIGPIPE, SIG_IGN);
#endif

    afterRedis();

    return 0;
}
```

Perhaps the memory increases steadily when reconnecting. Is there a problem with my code?

Thank you.

**Comment by michael-grunder** [comment] 2020-11-30 16:26
Hi @hsnks100,

The problem is that you're creating a new event loop (that never exits) each time you call `afterRedis()`.

[I modified your program so it exits after three calls to `afterRedis`](https://gist.github.com/michael-grunder/bbea36d68575b9743f011e481cc7cf24).

You can use Valgrind to show you where the leaks are:

```valgrind --leak-check=full ./your-program```

Here's the [memory leak report](https://gist.github.com/michael-grunder/96fea6dc5f03965837be997733f6a749)

**Comment by michael-grunder** [comment] 2020-11-30 22:14
I'm going to close the issue since it's not about a bug in Hiredis but if you have other questions feel free to ask.

**Closed by michael-grunder** 2020-11-30 22:14 UTC

**Comment by hsnks100** [comment] 2020-12-01 02:02
Thank you for the reply. However, in my case, disconnection occurs with the server every certain time and I need to reconnect. If there is no iteration variable and I have to reconnection indefinitely, can't I avoid the rick?

**Comment by michael-grunder** [comment] 2020-12-01 18:08
I'm not all that familiar with libevent, but generally speaking you would use events and timers to accomplish this sort of thing

See [this modified version of your program](https://gist.github.com/michael-grunder/fac7d47b5cf3123abe852b2d4753eac3) to get an idea how you might go about it.

Note that I changed the code to view all keyspace messages, so I could detect the string `shutdown` in order to make the program exit.  This is useful for detecting memory leaks.

The above program does leak one `redisAsyncContext`, which you could clean up if you wanted to.

**Comment by hsnks100** [comment] 2020-12-02 01:56
@michael-grunder Thanks for replying. 

Eventually there seems not to be a memory leak. I refered your modified version.
