### ISSUE TITLE
Solaris CC compiler is unable to use sds.h

### ISSUE THREAD

**Issue by mondaldebanjan** [redis/hiredis#952] opened 2021-05-13 05:44 UTC
Getting an error for "sds.h", line 53: Error: In this declaration "buf" is of an incomplete type "char[]". while comiling my c++ code in :
/opt/solarisstudio12.3//bin/CC -V
CC: Sun C++ 5.12 Linux_i386 2011/11/16

uname -i -o
x86_64 GNU/Linux

Is there any way so that I can use this library with sun compiler?

**Comment by michael-grunder** [comment] 2021-05-23 01:09
Hiredis requires C99 which I suspect is the cause of your issue.

I'm not familiar with the Solaris compiler, but does it not support C99?

**Comment by michael-grunder** [comment] 2021-05-23 19:21
Going to close this since it's not a bug in Hiredis but if you provide more context I'm happy to try to help getting it compiling for you.

**Closed by michael-grunder** 2021-05-23 19:21 UTC
