### ISSUE TITLE
After Linux is connected to redis, multithreaded data writing is stuck. The requirement is that up to 300 threads write JSON format data to redis.

### ISSUE THREAD

**Issue by 3293895182** [redis/hiredis#1051] opened 2022-03-19 08:58 UTC
![image](https://user-images.githubusercontent.com/58204505/159114477-811b5399-10fe-4a3f-b7a2-f511f475c00a.png)

**Comment by michael-grunder** [comment] 2022-04-19 00:49
Hi, sorry for the delayed response.

You cannot share a `redisContext` object across threads like you're attempting to do as hiredis does not contain any synchronization logic.

That said, if you truly have the need to write with 300 concurrent threads, it's unlikely a single `redis-server` will be able to process that volume anyway, as Redis is single-threaded.

One option would be to create a `redisContext` _per-thread_, and another would be to use async hiredis and a thread-safe append-only queue.  Push the messages you want to be delivered into the queue and then process them in the async callback.

**Comment by michael-grunder** [comment] 2022-04-19 00:49
Closing this as it's not a bug in Hiredis but happy to help answer any additional questions you have.

**Closed by michael-grunder** 2022-04-19 00:49 UTC
