### ISSUE TITLE
Bug in net.c

### ISSUE THREAD

**Issue by gemorin** [redis/hiredis#239] opened 2014-04-29 17:14 UTC
glibc ships with 2 prototypes for strerror_r: http://www.gnu.org/software/libc/manual/html_mono/libc.html#Error-Messages. 

One does not guarantee it will write to the specified buffer.  Therefore, in __redisSetError, if prefix is NULL, then buf could be left uninitialized.  If the prefix is set, then buf is not guaranteed to contain the error string.

Here is my suggested change:
```
--- a/hiredis/net.c
+++ b/hiredis/net.c
@@ -60,7 +60,17 @@
 
     if (prefix != NULL)
         len = snprintf(buf,sizeof(buf),"%s: ",prefix);
+#if !defined(__GLIBC__) || (!defined(_GNU_SOURCE) && (_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600))
     strerror_r(errno,buf+len,sizeof(buf)-len);
+#else
+    if (len < sizeof(buf)) {
+        char *errStr = strerror_r(errno,buf+len,sizeof(buf)-len);
+        if (errStr != buf+len) {
+            buf[len] = '\0';
+            strncat(buf + len, errStr, sizeof(buf)-len);
+        }
+    }
+#endif
     __redisSetError(c,type,buf);
 }
 
```

**Comment by mattsta** [comment] 2015-01-05 15:51
Not sure what this issue is trying to fix since the assumptions seem faulty?

> glibc ships with 2 prototypes for strerror_r:

Nope.  It has one.

> One does not guarantee it will write to the specified buffer.

Nope.  It writes to the buffer.

> if prefix is NULL, then buf could be left uninitialized

If prefix is NULL, then `len` is 0, which doesn't change anything.

> then buf is not guaranteed to contain the error string.

I don't see how?


Closing this because I can't make sense of the problem.

**Comment by gemorin** [comment] 2015-01-05 16:06
Yes, there is 2 flavors of strerror in glibc: https://sourceware.org/git/?p=glibc.git;a=blob;f=string/string.h#l416

 416    There are 2 flavors of `strerror_r', GNU which returns the string
 417    and may or may not use the supplied temporary buffer and POSIX one
 418    which fills the string into the buffer.
 419    To use the POSIX version, -D_XOPEN_SOURCE=600 or -D_POSIX_C_SOURCE=200112L
 420    without -D_GNU_SOURCE is needed, otherwise the GNU version is
 421    preferred.  */
 422 # if defined __USE_XOPEN2K && !defined __USE_GNU

**Comment by mattsta** [comment] 2015-01-05 16:11
Ah, going by the documentation linked above it wasn't clear.

Is the issue reproducible anywhere?  (is it a real problem or a theoretical problem?)

**Comment by gemorin** [comment] 2015-01-05 16:22
It's definitely not theoretical for me since I build hiredis without _GNU_SOURCE. I end up with the 2nd flavor and non-sensical error messages.  I can't comment how common this is though.
I think it'd be wise to support the 2 flavors out of the box.  I've been using the patch above since I posted it without any issues

**Comment by mattsta** [comment] 2015-01-05 19:17
Chromium takes the long way around: https://github.com/adobe/chromium/blob/cfe5bf0b51b1f6b9fe239c2a3c2f2364da9967d7/base/safe_strerror_posix.cc

**Comment by mattsta** [comment] 2015-01-05 19:52
Added to next maint release.

Thanks for explaining everything!

**Closed** 2015-01-22 21:06 UTC
Labels: approved
