### ISSUE TITLE
Can't compile hiredis in 32 bits

### ISSUE THREAD

**Issue by paulinhojpma** [redis/hiredis#920] opened 2021-01-30 21:30 UTC
Hi, I'm trying to compile hireredis in 32 bits, on a 64 bit architecture machine, 

`gcc -m32 -o test test.c  -lhiredis`

but it always returns with the following error message:

`/usr/bin/ld:  skipping incompatible /usr/local/lib/libhiredis.so when searching for -lhiredis
/usr/bin/ld: skipping incompatible  /usr/local/lib/libhiredis.a when searching for -lhiredis
/usr/bin/ld: cannot find  -lhiredis
collect2: error: ld returned 1 exit status
`

For information, I use an Ubuntu 20.04.1 LTS.
What am I doing wrong?

**Comment by michael-grunder** [comment] 2021-02-09 00:04
Are you sure you built hiredis in 32bit mode?

You'd need to do something like:
```bash
# In hiredis directory
$ make clean && make 32bit && sudo make install
```

Then you can verify it's built in 32-bit mode like so:
```bash
$ file /usr/local/lib/libhiredis.so.1.0.1-dev
/usr/local/lib/libhiredis.so.1.0.1-dev: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=0fe74b4f259538425195a8948540a8289a5bd950, with debug_info, not stripped                 
```

My guess is you've built 64-bit hiredis so your 32 bit program can't link to it.

**Comment by michael-grunder** [comment] 2021-02-09 17:57
I'm going to close the issue as it's not a bug in hiredis, but if you have more questions feel free to ask them here and I'll help.

**Closed by michael-grunder** 2021-02-09 17:57 UTC
