### ISSUE TITLE
EXEC without MULTI error

### ISSUE THREAD

**Issue by ijklsd** [redis/hiredis#725] opened 2019-10-31 15:24 UTC
I am a newbie at Redis and HiRedis, but I know my way around C coding. 

I have a C application that makes use of the HiRedis API. It does seem to work as I expected, but I have come across some issues that I just can't sort out.

I am using HiRedis 0.13.3, with Redis 4.0.9, from a C application under Linux. In this application I have a function F, invoked in a POSIX thread, that, in essence, consists of a loop where a number of invocations of redisCommand() are made. The command arguments to redisCommand() in this loop are the following:

       MULTI
       SMOVE
       HSET
       EXEC

This set of commands is executed 100 times in the loop.

This does what I expect, in that the SMOVE and HSET operations do what they are supposed to do - I have verified this using the redis-cli tool. I have, however, encountered the following issues:

1. When invoking the SMOVE or HSET commands from redisCommand(), the value in the 'type' field of the returned redisReply pointer can be either REDIS_REPLY_INTEGER or REDIS_REPLY_STATUS. Why? When I do the sequence above by hand, at the redis-cli tool, MULTI returns OK (obviously REDIS_REPLY_STATUS), SMOVE and HSET return QUEUED (which is REDIS_REPLY_STATUS as well), and EXEC returns an array with two integers, which I interpret to be the return values of the SMOVE and HSET commands, after they were queued.

2. The function F gets invoked a number of times without any problem (other than the issue above.) However, all of a sudden the redisCommand() invocation for 'EXEC' returns with REDIS_REPLY_ERROR in the 'type' field, and the following diagnostic in the 'str' field:

     ERR EXEC without MULTI

The thing is, I know for a fact that MULTI has been successfully invoked, as described in the sequence above - I have lots of tracing code that tells me that redisCommand(con, "MULTI") returns REDIS_REPLY_STATUS. 

Why would the redisCommand(con, "EXEC") invocation all of sudden think that there is no matching 'MULTI' when, in fact, there is one?

A few comments about the application:
1. It consists of a main thread M that carries out other HiRedis operations with a HiRedis context C.
2. M launches the thread that runs F, using a separate HiRedis context C'. C and C' are two different HiRedis contexts.
3. Ultimately, M will launch several threads where F will run concurrently, each instance with its own redisContext. For simplicity in this report, M is launching a single F thread - I have tested with M launching several F threads, and the issue is (unsurprisingly) still there.

**Comment by michael-grunder** [comment] 2019-11-03 20:06
Hi @ijklsd,

It's hard to say exactly what's happening with your application without a small program we can use to replicate the problem.

I think you've correctly diagnosed that you're getting out of sync somehow, and that the integer replies you're seeing are either from `HSET` or `SMOVE` when your application is expecting a reply from `MULTI`.

If you're truly working with a "share nothing" setup, then this should work in theory.  The symptoms you're describing (weird hard to reproduce failures and being out of sync) sure sounds threading related though. 😀

I wrote a little program that does what you're describing (several worker threads executing `MULTI...SMOVE...HSET...EXEC` in a loop, pulling jobs pushed to a list from the main thread, but I am not seeing the behavior you describe.

You could try using `valgrind --tool=helgrind` and see if anything immediately jumps out at you.

**Comment by michael-grunder** [comment] 2019-11-08 16:53
Were you able to solve your problem?

I'm going to close the issue because I don't think there is a bug here, but if you can provide an example program that triggers the problem I'm happy to investigate further.

**Closed by michael-grunder** 2019-11-08 16:53 UTC
