### ISSUE TITLE
Don't use -G to build shared object on Solaris

### ISSUE THREAD

**Issue by noloader** [redis/hiredis#757] opened 2020-02-01 15:05 UTC
Please don't use `-G` to build the shared object on Solaris. Instead, use `-shared`.

```
...
Generating hiredis.pc for pkgconfig...
gcc -G -o libhiredis.so -h libhiredis.so.0.14 -L/usr/local/lib -m64 -Wl,-R,'$ORIGIN/../lib' -Wl,-R,/usr/local/lib net.o hiredis.o sds.o async.o read.o
ar rcs libhiredis.a net.o hiredis.o sds.o async.o read.o
gcc -O3 -fPIC -g2 -O2 -m64 -march=native -fPIC -pthread -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb -o hiredis-test -L/usr/local/lib -m64 -Wl,-R,'$ORIGIN/../lib' -Wl,-R,/usr/local/lib -ldl -lnsl -lsocket test.o libhiredis.a
```

Here's the result of using `-G`:

```
ld.so.1: unittest: fatal: relocation error: R_AMD64_PC32: file /usr/local/lib/libhiredis.so.0.14: symbol _init: value 0x7f004e1390bd does not fit
gmake: *** [test] Killed
```

The failed self-test showed up when testing [Unbound](https://github.com/NLnetLabs/unbound).

**Comment by michael-grunder** [comment] 2020-02-03 01:27
Having done a bit of research it looks like you're right about this, but I don't have solaris boxes where I could test it.

The only thing I'm concerned about is whether the change might cause a regression in very old/obscure versions of Solaris.  In other words, can we simply change `-G` to `-shared` within our `SunOS` uname branch, or do we need to be more specific about it.

Do you happen to know?

**Comment by noloader** [comment] 2020-02-03 01:54
Hi Michael,

> The only thing I'm concerned about ... very old/obscure versions of Solaris

Ah, OK. Just my 2 cents here... I help maintain some other libraries. My rule of thumb is, don't break the common case for the obscure case. Make the obscure case the special case so things "just work" for the common case. In this context, the common case is Solaris 11.3 or 11.4, and the obscure case is Solaris 9.

As far as testing, I can give you SSH access to my test machines. For Solaris I use 11.3 i86pc (x86_64). It is a Core i5 4th gen, so you have AES, RDRAND and AVX. I need your `authorized_keys` file, if interested. Email me at *noloader*, gmail account.

[OpenCSW](https://www.opencsw.org/) provides free access to Solaris 9 through Solaris 11 on both Sparc and i86pc. See [Upstream Maintainers](https://www.opencsw.org/extend-it/signup/to-upstream-maintainers/) to request an account.

I believe the [GCC Compile Farm](https://cfarm.tetaneutral.net/) (Cfarm) provides access to the same machines via OpenCSW. Accounts are free to FOSS developers. See [Request an Account](https://cfarm.tetaneutral.net/users/new/) for the Cfarm.

**Comment by noloader** [comment] 2020-02-03 04:48
For what it is worth, here is how I patch the [hiredis recipe](https://github.com/noloader/Build-Scripts/blob/master/build-hiredis.sh#L90) in my build scripts:

```
IS_SUNC=$("$CC" -V 2>&1 | grep -i -c -E 'sun|studio')
IS_SOLARIS=$(uname -s | grep -i -c 'sunos')
...

# Awful Solaris 64-bit hack. Use -G for SunC, and -shared for GCC
if [[ "$IS_SOLARIS" -ne 0 && "$IS_SUNC" -eq 0 ]]; then
    sed 's/ -G / -shared /g' Makefile > Makefile.fixed
    mv Makefile.fixed Makefile; chmod +x Makefile
fi
```

**Comment by michael-grunder** [comment] 2020-02-03 18:58
> OK. Just my 2 cents here... I help maintain some other libraries. My rule of thumb is, don't break the common case for the obscure case

Yeah we're on the same page, and it certainly seems like `-G` is the obscure case now (especially given the line was last touched in 2011 via 608e29b375e49f7534f57edd1dc895c19ede0123).

Ideally we can make the change without breaking builds that are currently compiling although we have some leeway here since we're still pre 1.0.0.

**Comment by michael-grunder** [comment] 2020-04-17 04:35
What do you think about the change in 23e3bd48960e6862c5129ac1b86e94723f4a6ef2.

I can't use `grep -E` because apparently that doesn't exist in Solaris?  Or at least it threw an error in my Solaris VM.

I'm somewhat concerned about the portability of `egrep` but as far as I can tell this exists everywhere.

**Comment by michael-grunder** [comment] 2020-04-19 21:45
@noloader Unless you have an objection to 23e3bd4 I'm going to get it merged.  I tested building on Solaris both with SunStudio 12.6 and gcc and both worked for me.

Interestingly SunStudio does not like `-ggdb` but it didn't prevent building.

**Closed** 2020-04-23 21:16 UTC
