### ISSUE TITLE
 int redisKeepAlive(redisContext *c, int interval)  set in windows invalid

### ISSUE THREAD

**Issue by wb2712** [redis/hiredis#1100] opened 2022-09-02 01:23 UTC
```
int redisKeepAlive(redisContext *c, int **_interval_**) {
    int _**val**_ = 1;
    redisFD fd = c->fd;

    if (setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &_**val**_, sizeof(val)) == -1){
        __redisSetError(c,REDIS_ERR_OTHER,strerror(errno));
        return REDIS_ERR;
    }

    val = interval;
}
```

```
int win32_setsockopt(SOCKET sockfd, int level, int optname, const void ***_optval_**, socklen_t optlen) {
    int ret = 0;
    if ((level == SOL_SOCKET) && ((optname == SO_RCVTIMEO) || (optname == SO_SNDTIMEO))) {
        const struct timeval *tv = _**optval**_;
        DWORD timeout = tv->tv_sec * 1000 + tv->tv_usec / 1000;
        ret = setsockopt(sockfd, level, optname, (const char*)&timeout, sizeof(DWORD));
    } else {
        ret = setsockopt(sockfd, level, optname, (const char*)optval, optlen);
    }
    _updateErrno(ret != SOCKET_ERROR);
    return ret != SOCKET_ERROR ? ret : -1;
}
```

**Comment by michael-grunder** [comment] 2022-09-02 01:45
Hi, thanks for the report.

I'm not totally sure what the issue is exactly though.  Are you saying that the calculated timeval is incorrect in windows?

**Comment by wb2712** [comment] 2022-09-02 01:53
redisKeepAlive     ->  _interval_
not be used  in   win32_setsockopt

**Comment by michael-grunder** [comment] 2022-09-02 02:32
OK it looks like Windows is special and uses the platform-specific `SIO_KEEPALIVE_VALS` code, which is supposed to be set using [WSAIoctl](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsaioctl).

I don't really have a Windows machine but will attempt to put something together.

**Comment by wb2712** [comment] 2022-09-02 05:00
int redisKeepAlive(redisContext *c, int **_interval_**) {
    int _**val**_ = 1;
    redisFD fd = c->fd;

    if (setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &_**val**_, sizeof(val)) == -1)


setsockopt()   used   val,   not  _interval_.

**Comment by michael-grunder** [comment] 2022-09-02 18:25
I don't really follow.  

According to what I'm reading online, Windows does support toggling `SO_KEEPALIVE` via `setsockopt` which we appear to be doing.

What _isn't_ supported is setting the interval.  You can't do that with `setsockopt` in windows but must instead use `WSAIoctl` with `SIO_KEEPALIVE_VALS`.

**Comment by michael-grunder** [comment] 2022-09-02 19:54
PR: #1103

We'll make sure it's correct and then get it merged.

**Comment by michael-grunder** [comment] 2022-09-03 03:28
Comment on #1104

**Closed** 2022-09-03 19:39 UTC
Labels: bug
