### ISSUE TITLE
Problem when sending messages when TLS encrypted connection is used

### ISSUE THREAD

**Issue by R-15000** [redis/hiredis#1252] opened 2024-03-27 13:57 UTC
Hello,

   We are doing speed and load tests using Redis in pub/sub broker mode and Hiredis C API. 
   The tests consists of continuously sending messages both ways from a client A to a client B using the broker.

   We have an issue when sending messages when TLS encrypted connection is used.

Regarding our tests :

  - We have a client A which sends a message to the client B. The client B, after receiving the message from client A, replies to the client A from the message reception callback. We repeat this operation continuously to mesure the number of transactions per second.
  - To do so, we use a topic "client_A" for the client A to send the messages, the client B subscibes to this topic "client_A". 
    Also, the client B sends the messages to its own topic "client_B", the client A subscribes to this topic "client_B". 

When we don't use TLS encrypted connection, everything works just fine. But when we set TLS encrypted connection, the message reception seems ok but seems we have issues sending some messages.
In our case, when TLS is set, the client B still receives the message from the client A, then the receive callback is called normally, but when it sends the reply from the callback, it seems the reply is not sent.

We found a temporary way to bypass, in our client B code, in the main function, before the test starts, we add the following lines to send a message to a temporary topic (Used only once), then add 1 second sleep delay after calling event_base_loop : 

redisAsyncCommand(Redis_async_context_reply, callback, (char *) "pub", "Publish Temporary_topic Hello", 5);
event_base_loop(Base_reply, EVLOOP_NONBLOCK);
sleep(1);

If we do this bypass, we are able to send the reply from the client B callback and the test seems to work fine.

However, we face strange limitations and restrictions with this bypass : If we send the "Hello" message to the topic "client_A" (that is used by client B to send replies from the callback), insted of a temporary topic, it doesn't work in that case.
Also, when we bypass, in the main function, before the test starts, if we send another message on another topic, no matter which, after doing the bypass (by sending the Hello message to the temporary topic), it doesn't work either.

Technically, there is also a second bypass, if we add a sleep(1) in the client B callback, after calling redisAsyncCommand and event_base_loop, it works, but it is of course painfully slow (1 message per second only). So we cannot use this method.

If we don't use TLS encrypted connection, everything works fine, we don't need to bypass.

We are trying to find the origin of this issue which appears only when we use TLS in our case. 
We guess there is somewhere an additional delay with the first message or something like that, anyway something that causes perturbation with event_base_loop or maybe redisAsyncCommand.
We tried to check the result of redisAsyncCommand before calling event_base_loop, and the same for event_base_loop, there is no error returned. (However we are not sure this verification is 100% reliable, as we got issues with the API of another broker : The publish function return was ok, meaning the command was sent, but the message sending was still in progress for example.)

In the client B (and also the client A) program, we use 2 Hiredis contexts, one for message reception, one for message sending. In the main function, when the test is started, we call, in a while loop, event_base_loop for the reception context. We also tried to call event_base_loop for the message sending context in the main loop instead of calling it only inside the callback after a message is sent, but it doesn't help, we still have the issue.

Any help would be appreciated.

Thank you.

**Comment by michael-grunder** [comment] 2024-03-27 17:26
So if I understand this correctly

| Client | Publishes To | Subscribes To |
|--------|--------------|---------------|
| A      | Channel A    | Channel B     |
| B      | Channel B    | Channel A     |

I should be able to set this up pretty simply.  What are the messages themselves?  For the purposes of the throughput test I suppose just a ping back and forth would suffice?

**Comment by R-15000** [comment] 2024-03-28 09:50
Hi,

   Thanks for your reply. Yes, the channel mapping is correct. 

   The messages I send are just a simple struct, containing an union for the data (data can be either char * or another struct, however for my test I only send char * messages for now) : 

union Data
   {
      char buffer[256];
      struct foo bar;
   };

struct Payload
   {
      int Header;
      int Data_size;
      union Data Data;
   };

   Therefore in the test loop, the "Data" union contains char *.
   Client A sends simple strings like "A" or "test". I use fgets to set the string in the beginning of the test then the loop starts.
   Client B, after receiving, is supposed to reply "OK", using the same kind of message structure. 
   The Client A waits for the reply before sending the next message.
   When I use my bypass method in Client B, Client A receives the message. Client A and Client B are 2 different binaries.

   I use redisAsyncCommand and send "PUBLISH" commands (pub/sub mode), I am not sure sending a simple "PING" command and waiting for the "PONG" reply would reproduce exactly this issue.

   Without TLS, I don't have the problems.

   Thank you.

**Comment by michael-grunder** [comment] 2024-03-31 00:37
Hi,

I created a [test repo](https://github.com/michael-grunder/hiredis-async-pingpong) that does in general what you describe.

I only see around a 15-20% drop in performance when I enable TLS, which is about what I would expect.

When using the `pingpong` binary on my M1 mini:

## No TLS

```bash
❯ ./pingpong --message-len 1024
host: localhost, port: 6380, tls: false, message len: 1024
Subscribed to 'client_b' (1 subscribers)
Subscribed to 'client_a' (1 subscribers)
[1] 10001 messages in 161679 usec (61857.14/sec)
[2] 10000 messages in 130116 usec (76854.50/sec)
[3] 10000 messages in 133473 usec (74921.52/sec)
[4] 10000 messages in 131550 usec (76016.72/sec)
[5] 10000 messages in 131437 usec (76082.08/sec)
```

## TLS

```bash
❯ ./pingpong --message-len 1024 --tls
host: localhost, port: 16380, tls: true, message len: 1024
Subscribed to 'client_b' (1 subscribers)
Subscribed to 'client_a' (1 subscribers)
[1] 10001 messages in 194855 usec (51325.34/sec)
[2] 10000 messages in 162378 usec (61584.70/sec)
[3] 10000 messages in 161607 usec (61878.51/sec)
[4] 10000 messages in 162223 usec (61643.54/sec)
[5] 10000 messages in 162997 usec (61350.82/sec)
```

Running two `ping` binaries, each subscribing to a channel.

## No TLS

```bash
❯ ./ping --client a --message-len 1024
host: localhost, port: 6380, tls: false, subscribe: client_b, publish: client_a, message_len: 1024
Subscribed to 'client_b' (1 subscribers)
[1] 10000 messages in 3295072 usec (3034.84/sec)
[2] 10000 messages in 523002 usec (19120.39/sec)
[3] 10000 messages in 519755 usec (19239.83/sec)
[4] 10000 messages in 521787 usec (19164.91/sec)
[5] 10000 messages in 528890 usec (18907.52/sec)
```

## TLS

```bash
❯ ./ping --client a --message-len 1024 --tls
host: localhost, port: 16380, tls: true, subscribe: client_b, publish: client_a, message_len: 1024
Subscribed to 'client_b' (1 subscribers)
[1] 10000 messages in 7906296 usec (1264.81/sec)
[2] 10000 messages in 680303 usec (14699.33/sec)
[3] 10000 messages in 679131 usec (14724.70/sec)
[4] 10000 messages in 683073 usec (14639.72/sec)
[5] 10000 messages in 679075 usec (14725.91/sec)
```

Note that this is a very quick and dirty program just to replicate the general idea that you mentioned in your issue.  It has a variety of limitations such that you can't really run more than two `ping` binaries, as they'll exponentially overflow Redis' output buffer.

Let me know if the program is useful though to help narrow down what might be going on.

**Comment by R-15000** [comment] 2024-04-04 12:40
Hi,

   Thank you for your reply and sorry for not having replied earlier.

   I didn't have enough time to continue working on this issue until now. I will try to look at your test program in the next days and see if it works better with it on my server, and I will also compare with my code to see if I did something wrong in my code.

**Comment by michael-grunder** [comment] 2024-05-10 16:44
Can this (and the other) issue be closed?

If you have a reproducer program that demonstrates the performance problem I'm happy to help but I'm not able to replicate it.

**Comment by michael-grunder** [comment] 2024-05-28 17:41
Going to close this since I don't think there is a bug in hiredis here.

If you can provide more information or a program that demonstrates the behavior I'm happy to take a look.

**Closed by michael-grunder** 2024-05-28 17:41 UTC
