### ISSUE TITLE
How to compare reply->element[..index..] to a string

### ISSUE THREAD

**Issue by thebirdfromsea** [redis/hiredis#978] opened 2021-08-29 14:20 UTC
Hi, how to compare a redisreply object to a string?

``` REDIS_REPLY_ARRAY:

A multi bulk reply. The number of elements in the multi bulk reply is stored in
reply->elements. Every element in the multi bulk reply is a redisReply object as well
and can be accessed via reply->element[..index..].
Redis may reply with nested arrays but this is fully supported. 
```
I want to compare the reply->element[..index..] to a string. Let's say: ```reply->element[i]->str != "(null)"``` But this is not working now. 

How to do this?

**Comment by michael-grunder** [comment] 2021-10-31 19:21
There are many ways, but the simplest would be to use C's [strcmp](https://www.tutorialspoint.com/c_standard_library/c_function_strcmp.htm) family of functions.

```c
int main(void) {
    redisContext *c;
    redisReply *reply;

    c = redisConnect("localhost", 6379);
    assert(c != NULL && !c->err);

    reply = redisCommand(c, "GET key");
    if (reply && reply->type == REDIS_REPLY_STRING) {
        /* Compare strings with `strcmp` */
        if (!strcmp(reply->str, "test")) {
            printf("reply->str == 'test'\n");
        } else {
            printf("reply->str != 'test' (it is: '%s')\n", reply->str);
        }
    } else {
        printf("Reply is not a string or is NULL!\n");
    }

    if (reply) freeReplyObject(reply);
    redisFree(c);
}
```

**Comment by michael-grunder** [comment] 2021-10-31 19:22
Going to close this since it's not a bug in hiredis but I'm happy to help if you have other questions.

**Closed by michael-grunder** 2021-10-31 19:22 UTC
