### ISSUE TITLE
SSL AsyncConnection

### ISSUE THREAD

**Issue by TonySalesforce** [redis/hiredis#972] opened 2021-08-05 20:22 UTC
I'm using an older version of hiredis with ssl and async, but I'm unsure where is correct place to call redisSecureConnection, as it always return REDIS_OK even if redis-server is down. I've tried immediately after creating the redisAsyncContext, in the onConnectCallback, and finally before sending a redisAsyncCommand. Since it's always return REDIS_OK, there is no way to catch errors until a command is sent, but at that point it's difficult to figure out if redis-server was down or if it was an error in the command.

This does not happen for synchronous connection, redisSecureConnection will return REDIS_ERR if redis-server is down.

Thanks for the help!

```
loop = aeCreateEventLoop(64);

redisAsyncContext *c = redisAsyncConnect("127.0.0.1", 6379);
redisSecureConnection(&c.c, ....) // always return REDIS_OK
redisAeAttach(loop, c);
redisAsyncSetConnectCallback(c,connectCallback);
redisAsyncSetDisconnectCallback(c,disconnectCallback);
redisAsyncCommand(...);
```

**Comment by michael-grunder** [comment] 2021-08-05 23:50
There's actually a good example of this in the [Redis Sentinel](https://github.com/redis/redis/blob/3f3f678a4741e6af18230ee1862d9ced7af79faf/src/sentinel.c#L2419) code.

Your instinct is correct.  If `redisAsyncConnect` returns you a non-null context but relay is down, you can handle that in your connect callback normally.  If the connection does succeed then hiredis will attempt to secure the connection (which of course can also fail).

All that really happens under the hood is that hiredis stores the `SSL_CTX` internally and overrides the various read/write callbacks to use that context for SSL.

**Comment by michael-grunder** [comment] 2021-08-10 02:14
Going to close this as it's not a bug with hiredis but feel free to ask more questions if you have them and I'll do my best to answer.

**Closed by michael-grunder** 2021-08-10 02:14 UTC
