### ISSUE TITLE
How to know the number of non-existed keys in pipeline? 

### ISSUE THREAD

**Issue by thebirdfromsea** [redis/hiredis#971] opened 2021-08-04 12:43 UTC
Hi

I use pipeline and each time client send 5 commands to Redis server, including get and set. Is there a way I can know the number of non-existed keys from get in these 5 commands? 

Thanks

**Comment by michael-grunder** [comment] 2021-08-05 23:43
I don't think that's possible with only `GET` and `SET`.  If the keys are small and you have a new enough Redis instance you could use `GETSET`.

```bash
127.0.0.1:6379[2]> getset missing1 value1
(nil) <-- key didn't exist
127.0.0.1:6379[2]> getset exists1 new_value_1
"i_exist" <-- key did exist
127.0.0.1:6379[2]> getset exists2 new_value_2
"i_exist" <-- key did exist
127.0.0.1:6379[2]> getset missing2 value2
(nil) <-- key didn't exist
```

Another strategy would be using EVAL/LUA:

```
local exists=redis.call('exists', KEYS[1])
redis.call('set', KEYS[1], ARGV[1])
return exists
```

That script will set a key and return `1` if the key existed, and `0` if it didn't.

**Comment by michael-grunder** [comment] 2021-10-31 19:23
Closing since it's not a bug in hiredis but I hope you were able to solve your problem!

**Closed by michael-grunder** 2021-10-31 19:23 UTC
